---
- name: Include credentials variables
  ansible.builtin.include_vars: credentials.yml

- name: Install Docker
  ansible.builtin.package:
    name: docker
    state: absent

- name: Run proxmox-ntfy container
  community.general.docker_container:
    name: proxmox-ntfy
    image: ibacalu/proxmox-ntfy:latest
    state: started
    published_ports:
      - "8080:8080"
    env:
      NTFY_SERVER_URL: "{{ base_ntfy_server_url }}"
      PROXMOX_API_URL: "{{ ansible_host }}:8006"
      PROXMOX_USER: "{{ base_proxmox_user }}"
      PROXMOX_PASS: "{{ base_proxmox_password }}"
    recreate: true
    restart_policy: unless-stopped
