---
- name: Create pve-no-enterprise source list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-no-enterprise.list
    line: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    mode: "644"
    create: true
    state: present

- name: Remove pve-enterprise and ceph repository
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '^deb https://enterprise.proxmox.com'
    replace: '# deb https://enterprise.proxmox.com'
  loop:
    - /etc/apt/sources.list.d/pve-enterprise.list
    - /etc/apt/sources.list.d/ceph.list
